In [74]:
import pandas as pd
from imblearn.over_sampling import RandomOverSampler
from sklearn.preprocessing import StandardScaler

# load the imbalanced dataset
df = pd.read_csv('Creditcard_data.csv')


k = df.drop('Class', axis=1)
y = df['Class']
scaler=StandardScaler()
X=pd.DataFrame(scaler.fit_transform(k),columns=k.columns)

**SMOTE**

In [75]:
from imblearn.over_sampling import SMOTE, ADASYN




smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)



balanced_smote = pd.concat([pd.DataFrame(X_smote), pd.DataFrame(y_smote)], axis=1)

balanced_smote

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.648034,-0.914180,-0.247263,1.610900,0.868503,-0.303702,0.247620,0.136543,0.188336,0.449139,...,-0.038091,0.617686,-0.195625,0.111783,0.033076,-0.437881,0.366449,-0.014410,0.409447,0
1,-1.648034,1.057914,0.041770,-0.687243,0.129200,0.059272,-0.197113,-0.237378,0.171947,-0.256424,...,-0.378795,-0.892627,0.395078,-0.543138,0.123043,0.213082,-0.107521,0.114215,-0.333712,1
2,-1.642211,-0.913057,-1.328056,0.870859,0.074846,-0.453941,1.340056,0.784631,0.367913,-1.691257,...,0.399235,1.431487,2.649315,-1.105739,-1.029321,-0.334519,-0.261707,-0.153538,1.567910,0
3,-1.642211,-0.610030,-0.343153,0.890044,-0.913332,-0.004811,0.888345,0.134206,0.524325,-1.545829,...,-0.185878,0.168529,-0.418355,-1.888690,1.241390,-0.505691,0.130911,0.282230,0.277334,0
4,-1.636388,-0.758390,0.563316,0.653161,0.093332,-0.366460,-0.051563,0.551496,-0.256731,0.966396,...,-0.023514,1.475319,-0.270897,0.231472,-0.746053,0.990903,0.651959,0.834790,0.006685,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521,-0.289422,0.025922,0.256483,-0.139701,-0.124012,0.782774,-0.128340,0.351356,0.160218,-0.110295,...,-0.150080,-0.232813,0.286702,-1.582014,-2.603389,-0.128114,0.450836,0.611639,-0.342300,1
1522,0.029537,-0.106575,0.234174,0.074293,-0.114799,0.805147,-0.289387,0.468485,0.099130,-0.114014,...,-0.095237,-0.045719,0.091432,-1.099926,-1.893760,-0.315321,0.259490,0.392608,-0.342291,1
1523,-0.096155,-0.314824,0.817777,-1.511515,1.678488,-0.404719,-1.153607,-1.631869,0.815850,-1.573414,...,0.201150,-0.534620,-0.383486,0.534554,0.030788,0.237206,0.332452,-0.150509,-0.340727,1
1524,1.319927,-1.682807,-2.504715,1.090326,0.988919,1.907357,-0.104129,-1.652747,0.669605,0.651861,...,0.818982,1.704981,1.963396,-1.068327,-0.382794,1.026824,-0.636568,-0.301507,0.565217,1
1525,0.514610,-0.580903,0.049722,-0.016227,-0.474878,0.803686,-0.169835,0.185465,0.238271,-0.013268,...,-0.265596,-0.296496,-0.103137,-1.189035,-2.143817,0.297215,-0.367820,-0.331402,-0.342283,1

**SAMPLE SIZE DETECTION**

In [76]:
import pandas as pd
import math

# Load the credit card dataset


# Calculate sample size
p = 0.5
E = 0.05
z = 1.96
N =len(balanced_smote)
n=math.ceil((z**2 * p * (1-p)) / (E**2 ))
print("The required sample size is:", n)

The required sample size is: 385

**CLUSTER SAMPLING**

In [77]:
from imblearn.over_sampling._smote import cluster
import numpy as np
# Split the features and target variable
X = balanced_smote.drop('Class', axis=1)
y = balanced_smote['Class']

# Define the number of clusters
k = 385

# Create an array of cluster labels
cluster_labels = np.random.randint(0, k, size=len(X))

# Select a random sample of clusters
selected_clusters = np.random.choice(range(k), size=int(k*0.5), replace=False)

# Filter the data to include only the selected clusters
cluster_data = balanced_smote[np.isin(cluster_labels, selected_clusters)].reset_index(drop=True)
#cluster_data
len(cluster_data)
cluster_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.648034,-0.914180,-0.247263,1.610900,0.868503,-0.303702,0.247620,0.136543,0.188336,0.449139,...,-0.038091,0.617686,-0.195625,0.111783,0.033076,-0.437881,0.366449,-0.014410,0.409447,0
1,-1.648034,1.057914,0.041770,-0.687243,0.129200,0.059272,-0.197113,-0.237378,0.171947,-0.256424,...,-0.378795,-0.892627,0.395078,-0.543138,0.123043,0.213082,-0.107521,0.114215,-0.333712,1
2,-1.642211,-0.913057,-1.328056,0.870859,0.074846,-0.453941,1.340056,0.784631,0.367913,-1.691257,...,0.399235,1.431487,2.649315,-1.105739,-1.029321,-0.334519,-0.261707,-0.153538,1.567910,0
3,-1.607271,-0.361165,1.024008,0.193180,-0.618333,0.869269,0.219643,1.171198,-4.520600,0.735811,...,3.183528,-1.513526,0.272943,-1.042027,-1.233389,-0.153779,-4.090832,-3.840693,-0.140955,0
4,-1.566508,-4.037679,-4.832952,0.301717,1.153161,2.782984,-1.569520,-1.976538,0.263244,1.439669,...,-0.835039,1.782127,6.970693,0.071840,-1.387945,-1.330928,1.225981,3.475227,-0.110608,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
752,-1.050851,0.517437,0.193682,-0.514176,-0.036424,0.493980,-0.026687,0.038088,0.212947,-0.162107,...,-0.279171,-0.628073,0.481809,-1.574184,-2.143271,0.147849,0.393017,0.598555,-0.339089,1
753,-0.289422,0.025922,0.256483,-0.139701,-0.124012,0.782774,-0.128340,0.351356,0.160218,-0.110295,...,-0.150080,-0.232813,0.286702,-1.582014,-2.603389,-0.128114,0.450836,0.611639,-0.342300,1
754,0.029537,-0.106575,0.234174,0.074293,-0.114799,0.805147,-0.289387,0.468485,0.099130,-0.114014,...,-0.095237,-0.045719,0.091432,-1.099926,-1.893760,-0.315321,0.259490,0.392608,-0.342291,1
755,1.319927,-1.682807,-2.504715,1.090326,0.988919,1.907357,-0.104129,-1.652747,0.669605,0.651861,...,0.818982,1.704981,1.963396,-1.068327,-0.382794,1.026824,-0.636568,-0.301507,0.565217,1
756,0.514610,-0.580903,0.049722,-0.016227,-0.474878,0.803686,-0.169835,0.185465,0.238271,-0.013268,...,-0.265596,-0.296496,-0.103137,-1.189035,-2.143817,0.297215,-0.367820,-0.331402,-0.342283,1

**RANDOM SAMPLING**

In [78]:

# Split the features and target variable
X = balanced_smote.drop('Class', axis=1)
y = balanced_smote['Class']

# Perform simple random sampling
n = 385 # number of samples to select
random_sample = balanced_smote.sample(n, random_state=42)

# Split the features and target variable for the random sample
X_rs = random_sample.drop('Class', axis=1)
y_rs = random_sample['Class']
random_sample
#len(random_sample)
# X_rs
# y_rs

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1439,-0.885262,1.046789,0.114969,-0.505854,0.309534,-0.290655,-0.998729,-0.009912,-0.173152,0.067510,...,-0.459688,-1.147200,0.431615,0.553141,0.251105,0.108407,-0.164874,0.152358,-0.334016,1
76,-1.362691,-0.288018,0.172073,0.828795,-0.065633,-0.165827,0.077392,0.443399,0.372228,-0.225157,...,0.180928,0.849531,-0.069148,0.430655,-0.257060,0.771187,0.012733,0.217690,-0.043894,0
1010,0.795404,-1.604956,1.313868,-2.132587,2.572869,-0.336864,-1.199815,-2.787781,1.592724,-2.796411,...,0.724414,0.075639,-1.127180,0.427783,-0.252949,0.333624,0.584637,-0.542120,-0.346801,1
660,1.257810,1.107055,0.077227,-0.564843,0.329303,-0.386217,-1.018490,-0.093350,-0.132824,0.181444,...,-0.492140,-1.293815,0.494266,0.532037,0.186597,0.152371,-0.168331,0.167305,-0.337303,0
1132,1.636846,0.554202,-0.411353,-0.089679,0.400646,0.244456,-0.702577,-0.604293,0.080990,0.288081,...,-0.222560,-0.460826,0.573198,0.130877,0.022776,0.496892,-0.226447,0.012581,-0.340559,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,1.636327,-0.020770,0.269117,-1.178256,-0.808115,2.490535,2.756825,0.164823,1.177325,-0.187004,...,-0.142831,-0.287790,-0.327578,1.597088,0.266621,-1.173635,0.115606,0.189170,-0.282071,0
1074,-0.481323,0.318333,0.504085,-1.085618,1.075137,-0.373178,-1.086805,-0.924115,0.374445,-0.839317,...,-0.102388,-0.836490,-0.003403,0.541664,0.122475,0.197751,0.115193,-0.006704,-0.337603,1
867,1.387157,0.117962,0.142577,0.264704,0.085115,0.386279,-0.921649,0.506413,-0.146154,-0.053551,...,-0.138888,-0.127349,-0.162286,0.596379,0.480898,-0.516529,-0.311863,-0.157923,-0.341654,1
485,0.425073,0.926168,-0.052632,-1.151525,0.537210,0.504487,-0.030423,0.472082,0.004407,-0.748033,...,-0.377131,-1.242047,-0.104609,-1.090434,0.862019,-1.299224,-0.095785,0.130998,0.188163,0
188,-0.925941,0.990981,0.276873,-0.034668,1.816700,-0.250119,-0.475262,-0.041467,0.083375,-0.780950,...,-0.233722,-0.599827,0.640856,0.899736,0.166397,-0.437705,-0.076959,0.155354,-0.315757,0

**SYSTEMATIC SAMPLING**

In [79]:
p = 0.5
E = 0.06
z = 1.96
N =len(balanced_smote)
n=math.ceil((z**2 * p * (1-p)) / (E**2 ))

start = 0 # starting index of the sample
step = len(balanced_smote) // n # step size

systematic_sample =balanced_smote.iloc[start::step].head(n)

# Split the features and target variable for the systematic sample
X_ss = systematic_sample.drop('Class', axis=1)
y_ss = systematic_sample['Class']
systematic_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.648034,-0.914180,-0.247263,1.610900,0.868503,-0.303702,0.247620,0.136543,0.188336,0.449139,...,-0.038091,0.617686,-0.195625,0.111783,0.033076,-0.437881,0.366449,-0.014410,0.409447,0
5,-1.636388,-0.192446,0.633914,0.257889,-0.360811,0.388193,-0.154143,0.414400,0.383147,-0.613354,...,-0.350021,-0.762695,0.038903,-0.593983,-0.808430,0.171794,0.766416,0.352776,-0.328756,0
10,-1.589801,1.256685,-1.188350,0.037517,-1.320644,-1.791779,-0.643514,-1.816234,0.127775,-1.925704,...,-0.023303,0.677104,0.189919,0.809869,0.319129,-0.314642,0.064831,0.119713,-0.307866,0
15,-1.578154,-0.444749,0.109425,1.146374,-1.394556,-1.050967,-0.193430,-0.859532,0.073710,-0.462371,...,0.812456,2.390515,-0.603165,-0.100760,-0.357395,-0.227041,-0.679493,0.526472,-0.266442,0
20,-1.554861,0.673822,-1.346524,0.149387,0.436054,-1.080869,0.938884,-1.176616,0.606115,-0.473799,...,-0.493433,-0.782684,-0.029392,-0.485769,-0.098596,-0.919620,0.210151,0.289568,0.824650,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1310,1.597021,1.108737,0.125391,-0.551209,0.322035,-0.321902,-1.001450,-0.034447,-0.183797,0.051958,...,-0.479147,-1.193249,0.468694,0.556255,0.248244,0.148004,-0.151575,0.172521,-0.340533,1
1315,0.654637,-1.496824,-2.230606,0.041956,1.317917,0.902396,-1.000156,0.176846,-0.047564,-0.198665,...,0.741377,0.425387,3.197743,-0.248459,0.353171,-0.240149,-0.753134,0.186068,1.752456,1
1320,0.326350,1.107700,0.119494,-0.553267,0.322976,-0.327866,-1.002534,-0.038657,-0.179491,0.063244,...,-0.479725,-1.202730,0.469254,0.553404,0.242475,0.148313,-0.153429,0.172432,-0.337145,1
1325,-0.157232,0.470481,0.128924,-0.029311,0.170928,0.125762,-0.951530,0.307888,-0.154111,-0.001487,...,-0.261144,-0.520103,0.063774,0.578416,0.390458,-0.278807,-0.256981,-0.040024,-0.336935,1
1330,-1.211174,0.662536,0.152899,-0.560639,0.008040,0.377276,-0.072441,-0.035865,0.201940,-0.187428,...,-0.305917,-0.699096,0.458525,-1.297384,-1.534845,0.165362,0.258640,0.468527,-0.337646,1

**SRATIFIED SAMPLING**

In [80]:

import math
import random
n=math.ceil((1.96**2 * (0.25))/((0.2/2)**2))
stra_sampling=balanced_smote.groupby('Class', group_keys=False).apply(lambda x: x.sample(n))
stra_sampling

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
630,1.141344,-1.750066,1.254985,-0.228130,-0.844524,-0.274137,0.271758,-1.735901,-3.800137,0.133737,...,6.068587,-2.435665,1.132808,-0.062723,-0.890640,0.662271,1.430410,0.179467,-0.342260,0
510,0.541540,0.827754,-0.211634,0.620139,1.829692,-0.198339,1.492946,-1.227725,1.013115,0.241443,...,0.078712,0.810269,0.705791,-1.049624,-0.475025,0.089421,0.280757,0.149992,-0.289708,0
750,1.613034,-0.330276,0.598758,0.848862,0.119815,0.376590,-0.422912,0.657243,0.122757,-0.684453,...,-0.161366,-0.376847,0.062773,0.042958,-0.742399,-1.380415,0.355696,0.516833,-0.296790,0
219,-0.803651,1.004372,0.004608,-0.381342,0.672326,-0.191281,-0.294201,-0.211251,0.174803,-0.250892,...,0.260017,0.970684,-0.078400,0.379945,0.974089,-0.627961,0.016535,0.100789,-0.297245,0
389,0.005793,1.018946,-0.115360,-0.360302,0.955198,-0.426579,-0.465728,-0.207302,0.154993,0.665292,...,-0.176091,-0.087732,0.116226,0.598869,1.029271,-0.722085,0.015789,0.115981,-0.307411,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,1.234791,-1.022235,-0.125381,0.221742,-0.677446,0.779524,-0.354147,0.137853,0.233424,0.035443,...,-0.309067,-0.216635,-0.535357,-0.391759,-0.951176,0.430263,-1.134108,-1.200928,-0.341563,1
1214,0.926082,-0.438458,0.144610,0.707353,-0.063546,0.813562,-0.807506,0.789924,-0.094125,-0.138510,...,0.059343,0.492062,-0.520160,0.523267,0.599370,-0.881083,-0.397432,-0.347075,-0.341519,1
1218,-0.243978,0.007044,0.253304,-0.109212,-0.122699,0.785962,-0.151285,0.368044,0.151515,-0.110825,...,-0.142266,-0.206157,0.258881,-1.513328,-2.502284,-0.154787,0.423574,0.580432,-0.342299,1
182,-0.960881,1.106649,0.113520,-0.555352,0.323931,-0.333908,-1.003632,-0.042921,-0.175130,0.074677,...,-0.480311,-1.212335,0.469822,0.550516,0.236631,0.148626,-0.155307,0.172341,-0.333712,1
848,-0.403038,0.007607,0.228286,-0.315806,-0.217119,0.766285,0.016542,0.198906,0.237697,-0.083421,...,-0.230549,-0.427994,0.380846,-1.951177,-3.175340,0.154012,0.438240,0.595795,-0.342304,1

**CONVENIENCE**

In [81]:
convenience_sample=balanced_smote[balanced_smote['Amount']>0.01]
convenience_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,-1.648034,-0.914180,-0.247263,1.610900,0.868503,-0.303702,0.247620,0.136543,0.188336,0.449139,...,-0.038091,0.617686,-0.195625,0.111783,0.033076,-0.437881,0.366449,-0.014410,0.409447,0
2,-1.642211,-0.913057,-1.328056,0.870859,0.074846,-0.453941,1.340056,0.784631,0.367913,-1.691257,...,0.399235,1.431487,2.649315,-1.105739,-1.029321,-0.334519,-0.261707,-0.153538,1.567910,0
3,-1.642211,-0.610030,-0.343153,0.890044,-0.913332,-0.004811,0.888345,0.134206,0.524325,-1.545829,...,-0.185878,0.168529,-0.418355,-1.888690,1.241390,-0.505691,0.130911,0.282230,0.277334,0
8,-1.607271,-0.554394,0.058831,-0.958451,-0.442909,2.437170,2.908623,0.289852,1.095256,-0.412099,...,-0.128606,-0.281949,-0.457162,1.632725,0.602875,-0.840934,-0.038589,0.573246,0.124079,0
12,-1.589801,1.102850,-1.226979,-0.476374,-1.208741,-1.348959,-0.744812,-0.954448,-0.204845,-2.351407,...,-0.388704,-0.636566,0.348716,0.636498,0.108986,-0.780660,0.010184,0.213794,0.267218,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1475,0.207459,-0.776178,-1.581748,-0.123380,1.042780,0.560185,-1.001118,0.116014,-0.082874,-0.123003,...,0.403212,-0.027937,2.442650,-0.027302,0.320913,-0.132536,-0.587655,0.182269,1.175001,1
1483,1.490816,-0.031470,-0.904411,-0.291084,0.757707,0.215413,-1.000622,0.059050,-0.125206,-0.060461,...,0.055218,-0.482484,1.663067,0.204718,0.295561,-0.021966,-0.414431,0.178473,0.574754,1
1492,1.106677,-2.200674,-2.867306,0.231393,1.575523,1.262110,-0.974317,0.184969,0.006604,-0.248380,...,1.071392,0.900461,3.895512,-0.485665,0.363990,-0.309267,-0.910330,0.176200,2.279311,1
1499,1.417910,-0.439500,-1.273067,-0.198059,0.913629,0.407516,-1.000356,0.092391,-0.104122,-0.100377,...,0.246414,-0.228411,2.090466,0.078849,0.312334,-0.082778,-0.508540,0.180600,0.902365,1
1524,1.319927,-1.682807,-2.504715,1.090326,0.988919,1.907357,-0.104129,-1.652747,0.669605,0.651861,...,0.818982,1.704981,1.963396,-1.068327,-0.382794,1.026824,-0.636568,-0.301507,0.565217,1

**SNOWBALL**

In [82]:
df_snowball = balanced_smote[balanced_smote['Class'] == 1].sample(n=200, random_state=42)

# add subsequent participants based on referrals from the initial participants
for i in range(5):
    referrals = balanced_smote[balanced_smote['Class'] == 0].sample(n=40, random_state=42)
    df_snowball = pd.concat([df_snowball, referrals])
    df_snowball = df_snowball.drop_duplicates()

df_snowball

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
1120,0.126421,-0.331948,0.125260,-0.142957,-0.365839,0.787865,-0.090992,0.191151,0.238028,-0.042945,...,-0.250770,-0.352123,0.101600,-1.511441,-2.580179,0.236637,-0.026835,0.060827,-0.342292,1
1022,1.109162,-2.014689,-2.505305,0.284565,1.386692,1.199636,-0.982771,0.317330,-0.025496,-0.256089,...,0.958540,0.846273,3.391004,-0.334711,0.417180,-0.425757,-0.857586,0.118538,2.000341,1
1512,-0.696126,0.897069,0.118595,-0.382052,0.273525,-0.182474,-0.986467,0.072650,-0.168205,0.049586,...,-0.408108,-0.984285,0.336053,0.559707,0.287308,0.007812,-0.188803,0.102379,-0.334774,1
956,1.350221,-0.932091,-0.010970,0.538186,-0.456325,0.861767,-0.586306,0.485434,0.081694,-0.021422,...,-0.125705,0.185664,-0.613177,0.061666,-0.304571,-0.179836,-0.874127,-0.911054,-0.342260,1
1096,-0.281729,-0.009769,0.666640,-1.306318,1.387793,-0.389523,-1.121422,-1.290873,0.603181,-1.219726,...,0.054905,-0.680061,-0.200362,0.537979,0.074963,0.218197,0.227776,-0.081224,-0.339222,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
605,1.019054,1.077418,-0.343257,-1.181305,-0.157614,1.448277,3.013187,-1.450910,1.319680,0.440940,...,0.108048,0.297969,-0.041595,1.606652,0.902970,-0.733265,0.140038,0.188569,-0.281565,0
535,0.698770,0.677465,-2.429471,-0.207131,-0.789290,-2.055683,0.164822,-1.401002,0.004825,-0.915281,...,0.073888,0.272113,-1.280447,-0.042250,0.806997,-0.054110,-0.009656,0.395608,1.735934,0
34,-1.496628,-0.277014,0.552683,0.461501,-0.109745,0.399760,-0.058861,0.669048,0.286026,-0.290855,...,0.073304,0.500189,-0.409394,0.005239,-0.037776,-1.190818,-0.338028,0.152695,-0.338366,0
32,-1.496628,-0.272782,0.560037,0.457788,-0.111429,0.382017,-0.048051,0.690383,0.281595,-0.292080,...,0.069072,0.502774,-0.405043,0.005686,-0.036147,-1.189646,-0.321344,0.145072,-0.316263,0
502,0.500777,0.874020,-0.833814,0.209888,-0.110111,-0.660421,1.037701,-1.401957,0.946849,1.667154,...,-0.170185,0.134134,0.805612,-0.957130,-0.944093,2.130866,-0.004812,0.073276,-0.182278,0

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
samples=[cluster_data,random_sample,systematic_sample,stra_sampling,df_snowball]
f_accuracy=[]
for i in samples:
  acc=[]
  X_train, X_test, y_train, y_test = train_test_split( 
   i.drop('Class',axis=1), i['Class'], test_size = 0.25, random_state = 42)
  #DecisionTree
  clf=DecisionTreeClassifier()
  clf.fit(X_train,y_train)
  y_pred=clf.predict(X_test)
  accuracy=accuracy_score(y_test,y_pred)
  acc.append(accuracy)
  #SVM
  classifier = SVC(kernel = 'rbf', random_state = 0)
  classifier.fit(X_train, y_train)
  y_pred=classifier.predict(X_test)
  accuracy=accuracy_score(y_test,y_pred)
  acc.append(accuracy)
  #Naive_Bayes
  gnb = GaussianNB()
  gnb.fit(X_train, y_train)
  y_pred = gnb.predict(X_test)
  accuracy=accuracy_score(y_test,y_pred)
  acc.append(accuracy)
  #KNN
  knn = KNeighborsClassifier()
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  accuracy=accuracy_score(y_test,y_pred)
  acc.append(accuracy)
  #RandomForest
  clf = RandomForestClassifier(n_estimators = 100)  
  clf.fit(X_train, y_train)
  y_pred = clf.predict(X_test)
  accuracy=accuracy_score(y_test,y_pred)
  acc.append(accuracy)
  f_accuracy.append(acc)

In [90]:
f_accuracy

[[0.968421052631579,
  0.9736842105263158,
  0.7684210526315789,
  0.8947368421052632,
  0.9947368421052631],
 [0.9381443298969072,
  0.9278350515463918,
  0.7835051546391752,
  0.7938144329896907,
  0.979381443298969],
 [0.9552238805970149,
  0.8805970149253731,
  0.6417910447761194,
  0.7313432835820896,
  1.0],
 [0.9387755102040817,
  0.9591836734693877,
  0.7959183673469388,
  0.8163265306122449,
  0.9795918367346939],
 [0.95, 0.9166666666666666, 0.8333333333333334, 0.8, 0.95]]

In [86]:
mm=['DecisionTree','SVM','NaiveBayes','KNN','RandomForest']
acc_score=pd.DataFrame(mm)
acc_score['cluster']=f_accuracy[0]
acc_score['Random']=f_accuracy[1]
acc_score['systematic']=f_accuracy[2]
acc_score['stratified']=f_accuracy[3]
acc_score['snowball']=f_accuracy[4]
acc_score

              0   cluster    Random  systematic  stratified  snowball
0  DecisionTree  0.986842  0.931034    0.876543    0.932203  0.944444
1           SVM  0.978070  0.931034    0.913580    0.949153  0.986111
2    NaiveBayes  0.736842  0.836207    0.753086    0.847458  0.902778
3           KNN  0.877193  0.818966    0.851852    0.796610  0.875000
4  RandomForest  0.991228  0.982759    0.987654    1.000000  0.972222